// Code generated by Kitex v0.9.1. DO NOT EDIT.

package greetservice

import (
	"context"
	helloworld "github.com/BuyandshipDemo/helloworld/kitex_gen/buyandship/marketplace/helloworld"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Greet(ctx context.Context, req *helloworld.GreetReq, callOptions ...callopt.Option) (r *helloworld.GreetResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kGreetServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kGreetServiceClient struct {
	*kClient
}

func (p *kGreetServiceClient) Greet(ctx context.Context, req *helloworld.GreetReq, callOptions ...callopt.Option) (r *helloworld.GreetResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Greet(ctx, req)
}
